version: '3.8'

services:
  # Database
  db:
    image: mysql:8.0
    container_name: wp_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - wp_network

  # WordPress (pinned to 6.4.1)
  wordpress:
    depends_on:
      - db
    image: wordpress:6.4.1
    container_name: wp_site
    restart: always
    ports:
      - "4000:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wp_data:/var/www/html                    # ← FIXED: wp_data (not wp_)
      - ./php-conf/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    networks:
      - wp_network

  # phpMyAdmin (Optional)
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    container_name: wp_phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: somewordpress
    networks:
      - wp_network

volumes:
  db_data:
  wp_data:          # ← This is the named volume you're mounting

networks:
  wp_network:
    driver: bridge